# Generated by Django 5.2.12 on 2026-03-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_total_amount_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
