# Generated by Django 5.2.12 on 2026-04-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_guest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('served', 'Served'), ('requested', 'Requested'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
