version: "3.9"

services:
  backend:
    build: ./Backend/scan2serve
    env_file:
      - ./Backend/scan2serve/.env
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
    depends_on:
      - backend

volumes:
  static_volume: