# Generated by Django 5.2.12 on 2026-04-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='table',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
