# Generated by Django 5.2.12 on 2026-04-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_capacity_table_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
