server {
    listen 80;

    # React frontend
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }

    # Django static files
    location /static/ {
        alias /static/;
    }

    # Django backend routes
    location ~ ^/(admin|menu|users|orders|tables|chat|analytics) {
        proxy_pass http://backend:8000;
        include /etc/nginx/proxy_params;
    }
}