# server {
#     listen 80;

#     client_max_body_size 20M;

#     # 1. React static files (VERY IMPORTANT - first match)
#     location /static/ {
#         root /usr/share/nginx/html;
#     }

 

#     # 2. Django admin static (override)
#     location /static/admin/ {
#         alias /static/admin/;
#     }

#     # ==============================
#     # Django media files (UPLOADS)
#     # ==============================
#     location /media/ {
#         alias /app/media/;
#     }


#     # 3. React frontend
#     location / {
#         root /usr/share/nginx/html;
#         try_files $uri /index.html;
#     }

#     # 4. Django backend
#     location ~ ^/(admin|menu|users|orders|tables|chat|analytics) {
#         proxy_pass http://backend:8000;
#         include /etc/nginx/proxy_params;
#     }
# }

# 1. Redirect all HTTP traffic to HTTPS
server {
    listen 80;
    server_name scan2serve.online; 

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# 2. HTTPS Server Block
server {
    listen 443 ssl;
    server_name scan2serve.online;

    client_max_body_size 20M;

    # SSL Certificate Paths (Managed by Certbot)
    ssl_certificate /etc/letsencrypt/live/scan2serve.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/scan2serve.online/privkey.pem;

    # Security Optimizations
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # React static files
    location /static/ {
        root /usr/share/nginx/html;
    }

    # Django admin static
    location /static/admin/ {
        alias /static/admin/;
    }

    # Django media files
    location /media/ {
        alias /app/media/;
    }

    # React frontend
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }

    # Django backend
    location ~ ^/(admin|menu|users|orders|tables|chat|analytics) {
        proxy_pass http://backend:8000;
        include /etc/nginx/proxy_params;
        
        # Crucial for Django to know the request was HTTPS
        proxy_set_header X-Forwarded-Proto https;
    }
}