server {
    listen 80;

    # 1. React static files (VERY IMPORTANT - first match)
    location /static/ {
        root /usr/share/nginx/html;
    }

    # 2. Django admin static (override)
    location /static/admin/ {
        alias /static/admin/;
    }

    # 3. React frontend
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }

    # 4. Django backend
    location ~ ^/(admin|menu|users|orders|tables|chat|analytics) {
        proxy_pass http://backend:8000;
        include /etc/nginx/proxy_params;
    }
}